default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: portfolio-creator_development

test:
  <<: *default
  database: portfolio-creator_test